name: ItemMail
main: taco.itemmail.ItemMailMain
version: 3.0.1
description: An easier way to trade
depend: [TacoAPI]
commands:
  im:
    description: ItemMail commands and help
    aliases: [imail, itemmail]