name: ItemMail
main: com.kill3rtaco.itemmail.ItemMailMain
version: 4.0.0
description: An easier way to trade
depend: [TacoAPI]
commands:
  im:
    description: ItemMail commands and help
    aliases: [imail, itemmail]